// import { Model, Sequelize } from "sequelize";

// import type { InferAttributes, InferCreationAttributes } from "sequelize";

// const sequelize = new Sequelize("sqlite::memory:");

// // const User = sequelize.define("User", {
// //   username: DataTypes.STRING,
// //   birthday: DataTypes.DATE,
// // });

// // model Assistant {
// //     key   String @id // eg. homeFeatures
// //     oaiId String @unique // generated by openAi
// //   }

// // export const Assistant = sequelize.define("Assistant", {
// //   appId: DataTypes.STRING,
// //   oaiId: DataTypes.STRING,
// // });

// // const jane = await Assistant.create({
// //     username: 'janedoe',
// //     birthday: new Date(1980, 6, 20),
// //   });

// class Assistant extends Model<
//   InferAttributes<Assistant>,
//   InferCreationAttributes<Assistant>
// > {
//   // 'CreationOptional' is a special type that marks the field as optional
//   // when creating an instance of the model (such as using Model.create()).
//   declare appId: string;
//   declare oaiId: string;
//   // other attributes...
// }

// //   import { Model, InferAttributes, InferCreationAttributes, CreationOptional } from 'sequelize';

// // order of InferAttributes & InferCreationAttributes is important.
// // class User extends Model<InferAttributes<User>, InferCreationAttributes<User>> {
// //   // 'CreationOptional' is a special type that marks the field as optional
// //   // when creating an instance of the model (such as using Model.create()).
// //   declare id: CreationOptional<number>;
// //   declare name: string;
// //   // other attributes...
// // }

// const jane = await Assistant.create({
//   appId: "janedoe",
//   oaiId: "asdasd",
// });
